services:
  postgres:
    container_name: postgres_judo
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prestigio123
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
